name: 'Setup Rust Environment'
description: 'Sets up Rust toolchain with caching and optional components'

inputs:
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: 'stable'
  components:
    description: 'Additional components to install (comma-separated)'
    required: false
    default: 'rustfmt,clippy'
  targets:
    description: 'Target architectures to install (comma-separated)'
    required: false
    default: ''
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: 'default'
  install-cargo-audit:
    description: 'Whether to install cargo-audit'
    required: false
    default: 'false'
  install-git-cliff:
    description: 'Whether to install git-cliff'
    required: false
    default: 'false'

outputs:
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}
  rust-version:
    description: 'Installed Rust version'
    value: ${{ steps.rust-info.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Get Rust info
      id: rust-info
      shell: bash
      run: |
        echo "version=$(rustc --version)" >> $GITHUB_OUTPUT
        echo "🦀 Rust version: $(rustc --version)"

    - name: Setup cargo cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-cargo-

    - name: Install cargo-audit
      if: inputs.install-cargo-audit == 'true'
      shell: bash
      run: |
        if ! command -v cargo-audit &> /dev/null; then
          echo "📦 Installing cargo-audit..."
          cargo install cargo-audit
        else
          echo "✅ cargo-audit already installed"
        fi

    - name: Install git-cliff
      if: inputs.install-git-cliff == 'true'
      shell: bash
      run: |
        if ! command -v git-cliff &> /dev/null; then
          echo "📦 Installing git-cliff..."
          cargo install git-cliff
        else
          echo "✅ git-cliff already installed"
        fi

    - name: Validate tools installation
      shell: bash
      run: |
        echo "🔍 Validating installed tools..."
        
        # Always validate core tools
        rustc --version || (echo "❌ rustc not found" && exit 1)
        cargo --version || (echo "❌ cargo not found" && exit 1)
        
        # Validate optional components
        if [[ "${{ inputs.components }}" == *"rustfmt"* ]]; then
          cargo fmt --version || (echo "❌ rustfmt not found" && exit 1)
          echo "✅ rustfmt validated"
        fi
        
        if [[ "${{ inputs.components }}" == *"clippy"* ]]; then
          cargo clippy --version || (echo "❌ clippy not found" && exit 1) 
          echo "✅ clippy validated"
        fi
        
        # Validate optional tools
        if [[ "${{ inputs.install-cargo-audit }}" == "true" ]]; then
          cargo audit --version || (echo "❌ cargo-audit not found" && exit 1)
          echo "✅ cargo-audit validated"
        fi
        
        if [[ "${{ inputs.install-git-cliff }}" == "true" ]]; then
          git-cliff --version || (echo "❌ git-cliff not found" && exit 1)
          echo "✅ git-cliff validated"
        fi
        
        echo "🎉 All tools validated successfully!"

    - name: Cache info
      shell: bash
      run: |
        if [ "${{ steps.cache.outputs.cache-hit }}" = "true" ]; then
          echo "🎯 Cache hit! Dependencies restored from cache"
        else
          echo "📦 Cache miss. Dependencies will be cached for next run"
        fi